# Generated by Django 5.0.2 on 2025-11-29 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fleet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nama Armada")),
                (
                    "fleet_type",
                    models.CharField(
                        choices=[
                            ("Small", "Small (Pickup/Van)"),
                            ("Medium", "Medium (CDE)"),
                            ("Large", "Large (CDD)"),
                            ("Heavy", "Heavy (Fuso/Tronton)"),
                        ],
                        default="Small",
                        max_length=20,
                        verbose_name="Tipe",
                    ),
                ),
                (
                    "capacity",
                    models.CharField(
                        help_text="Contoh: 5 Ton",
                        max_length=50,
                        verbose_name="Kapasitas",
                    ),
                ),
                (
                    "dimension",
                    models.CharField(
                        help_text="Contoh: 4.2 x 1.9 x 1.8 m",
                        max_length=50,
                        verbose_name="Dimensi",
                    ),
                ),
                (
                    "volume",
                    models.CharField(
                        help_text="Contoh: 14 CBM", max_length=50, verbose_name="Volume"
                    ),
                ),
                (
                    "description",
                    models.TextField(max_length=200, verbose_name="Deskripsi"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="fleets/",
                        verbose_name="Foto Armada",
                    ),
                ),
                ("order", models.IntegerField(default=1, verbose_name="Urutan Tampil")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Armada",
                "verbose_name_plural": "Daftar Armada",
                "ordering": ["order"],
            },
        ),
    ]
