# Generated by Django 5.0.2 on 2025-12-14 19:10

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Fleet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nama Armada"
                    ),
                ),
                (
                    "fleet_type",
                    models.CharField(
                        choices=[
                            ("ECONOMY", "Ekonomi (MPV / Blind Van)"),
                            ("PICKUP", "Pickup (Bak / Box)"),
                            ("ENGKEL", "Engkel CDE (4 Roda)"),
                            ("DOUBLE", "Double CDD (6 Roda)"),
                            ("FUSO", "Fuso / Truk Besar"),
                            ("TRONTON", "Tronton / Wingbox"),
                            ("TRAILER", "Trailer / Container"),
                        ],
                        default="PICKUP",
                        max_length=20,
                    ),
                ),
                (
                    "capacity",
                    models.CharField(
                        choices=[
                            ("ECO_MPV", "Ekonomi MPV (1.7m x 1m x 0.8m) - Max 350 Kg"),
                            (
                                "BLIND_VAN",
                                "Blind Van (GranMax) (2.1m x 1.5m x 1.2m) - Max 0.7 Ton / 4 m³",
                            ),
                            (
                                "PICKUP_BAK",
                                "Pickup Bak (2.4m x 1.6m x 1.2m) - Max 800 Kg / 5 m³",
                            ),
                            (
                                "PICKUP_BOX",
                                "Pickup Box (2.4m x 1.6m x 1.2m) - Max 1 Ton / 5 m³",
                            ),
                            (
                                "L300_BAK",
                                "Pickup L300 Bak (2.4m x 1.6m x 1.2m) - Max 1 Ton / 6 m³",
                            ),
                            (
                                "CDE_BAK",
                                "Engkel (CDE) Bak (3.1m x 1.6m x 1.6m) - Max 2.5 Ton / 9 m³",
                            ),
                            (
                                "CDE_BOX",
                                "Engkel (CDE) Box (3.1m x 1.7m x 1.7m) - Max 2.2 Ton / 9 m³",
                            ),
                            (
                                "CDD_BAK",
                                "Double (CDD) Bak (4.2m x 1.9m x 2m) - Max 5 Ton / 16 m³",
                            ),
                            (
                                "CDD_BOX",
                                "Double (CDD) Box (4.2m x 2m x 2m) - Max 5 Ton / 17 m³",
                            ),
                            (
                                "CDD_LONG",
                                "CDD Long Box (5.3m x 2m x 2.2m) - Max 5.5 Ton / 24 m³",
                            ),
                            (
                                "FUSO_BAK",
                                "Fuso Ringan Bak (5.7m x 2.3m x 2.3m) - Max 8 Ton / 30 m³",
                            ),
                            (
                                "FUSO_BOX",
                                "Fuso Ringan Box (5.7m x 2.3m x 2.3m) - Max 8 Ton / 30 m³",
                            ),
                            (
                                "FUSO_BERAT",
                                "Fuso Berat (Hino Ranger) (7m x 2.4m x 2.3m) - Max 15 Ton / 40 m³",
                            ),
                            (
                                "TRONTON_BAK",
                                "Tronton Bak (9.5m x 2.4m x 2.3m) - Max 18 Ton / 50 m³",
                            ),
                            (
                                "WINGBOX",
                                "Tronton Wingbox (9.4m x 2.4m x 2.4m) - Max 18 Ton / 55 m³",
                            ),
                            (
                                "TRAILER_20",
                                "Trailer 20 Feet (6m x 2.4m x 2.4m) - Max 20 Ton / 33 m³",
                            ),
                            (
                                "TRAILER_40",
                                "Trailer 40 Feet (12m x 2.4m x 2.4m) - Max 28 Ton / 67 m³",
                            ),
                        ],
                        default="CDE_BAK",
                        max_length=50,
                    ),
                ),
                (
                    "tomtom_travel_mode",
                    models.CharField(
                        choices=[("truck", "Truk Besar"), ("car", "Mobil/Van")],
                        default="truck",
                        help_text="Mode routing API TomTom",
                        max_length=10,
                    ),
                ),
                (
                    "max_weight_kg_limit",
                    models.IntegerField(
                        default=1000, verbose_name="Batas Berat Standar (Kg)"
                    ),
                ),
                (
                    "max_volume_cbm_limit",
                    models.FloatField(
                        default=5.0, verbose_name="Batas Volume Standar (m3)"
                    ),
                ),
                (
                    "surcharge_weight_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Biaya tambahan per Kg jika over weight",
                        max_digits=10,
                    ),
                ),
                (
                    "surcharge_volume_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Biaya tambahan per m3 jika over volume",
                        max_digits=10,
                    ),
                ),
                (
                    "dimension",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Dimensi Custom",
                    ),
                ),
                (
                    "volume",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Volume Custom",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="fleets/"),
                ),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "0. Master Data Jenis Armada",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="MasterPricingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fleet_type",
                    models.CharField(
                        choices=[
                            ("ECONOMY", "Ekonomi (MPV / Blind Van)"),
                            ("PICKUP", "Pickup (Bak / Box)"),
                            ("ENGKEL", "Engkel CDE (4 Roda)"),
                            ("DOUBLE", "Double CDD (6 Roda)"),
                            ("FUSO", "Fuso / Truk Besar"),
                            ("TRONTON", "Tronton / Wingbox"),
                            ("TRAILER", "Trailer / Container"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="Kategori Armada",
                    ),
                ),
                (
                    "base_fare",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "base_rate_per_km",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                ("min_distance_km", models.IntegerField(default=10)),
                (
                    "min_price_lumpsum",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                (
                    "sla_express_multiplier",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("1.5"), max_digits=3
                    ),
                ),
                (
                    "loading_unloading_rate",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "doc_return_fee",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "0. Master Pricing Rules (HPP)",
            },
        ),
        migrations.CreateModel(
            name="Promo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("promo_code", models.CharField(max_length=20, unique=True)),
                ("image", models.ImageField(upload_to="promos/")),
                ("valid_until", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "5. Promo & Voucher",
            },
        ),
        migrations.CreateModel(
            name="CachedDistance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin_lat", models.DecimalField(decimal_places=8, max_digits=12)),
                ("origin_lng", models.DecimalField(decimal_places=8, max_digits=12)),
                ("dest_lat", models.DecimalField(decimal_places=8, max_digits=12)),
                ("dest_lng", models.DecimalField(decimal_places=8, max_digits=12)),
                ("distance_km", models.DecimalField(decimal_places=2, max_digits=10)),
                ("duration_minutes", models.IntegerField()),
                (
                    "toll_fee_idr",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("cached_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Cached Distance",
                "unique_together": {
                    ("origin_lat", "origin_lng", "dest_lat", "dest_lng")
                },
            },
        ),
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="Nomor WA (Username)"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        max_length=100, verbose_name="Nama Perusahaan/Shipper"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Kota/Kabupaten Domisili",
                    ),
                ),
                (
                    "address",
                    models.TextField(
                        blank=True, null=True, verbose_name="Alamat Detail Perusahaan"
                    ),
                ),
                (
                    "risk_status",
                    models.CharField(
                        choices=[
                            ("SAFE", "🟢 Aman / Verified"),
                            ("CAUTION", "🟡 Waspada (Perlu Review)"),
                            ("BLACKLIST", "🔴 Blacklist (Dilarang)"),
                        ],
                        default="CAUTION",
                        max_length=20,
                    ),
                ),
                ("admin_risk_notes", models.TextField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "1. Data Customer (Shipper)",
            },
        ),
        migrations.CreateModel(
            name="MitraArmada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name_ktp", models.CharField(max_length=150)),
                ("phone_number", models.CharField(max_length=15, unique=True)),
                ("emergency_name", models.CharField(max_length=100)),
                ("emergency_phone", models.CharField(max_length=15)),
                (
                    "risk_status",
                    models.CharField(
                        choices=[
                            ("SAFE", "🟢 Aman / Verified"),
                            ("CAUTION", "🟡 Waspada (Perlu Review)"),
                            ("BLACKLIST", "🔴 Blacklist (Dilarang)"),
                        ],
                        default="CAUTION",
                        max_length=20,
                    ),
                ),
                ("admin_risk_notes", models.TextField(blank=True)),
                ("domicile_city", models.CharField(default="Jakarta", max_length=100)),
                ("domicile_address", models.TextField()),
                (
                    "mitra_type",
                    models.CharField(
                        choices=[
                            ("OWNER_OPERATOR", "Pemilik Unit & Supir"),
                            ("DRIVER", "Supir"),
                        ],
                        default="OWNER_OPERATOR",
                        max_length=20,
                    ),
                ),
                ("ktp_photo", models.ImageField(upload_to="dokumen/ktp/")),
                ("sim_photo", models.ImageField(upload_to="dokumen/sim/")),
                ("selfie_photo", models.ImageField(upload_to="dokumen/selfie/")),
                (
                    "skck_photo",
                    models.ImageField(blank=True, null=True, upload_to="dokumen/skck/"),
                ),
                (
                    "bank_name",
                    models.CharField(
                        choices=[
                            ("BCA", "BCA"),
                            ("BRI", "BRI"),
                            ("MANDIRI", "Mandiri"),
                            ("BNI", "BNI"),
                            ("LAINNYA", "Lainnya"),
                        ],
                        default="BCA",
                        max_length=20,
                    ),
                ),
                ("bank_account_number", models.CharField(max_length=50)),
                ("bank_account_holder", models.CharField(max_length=150)),
                (
                    "document_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Menunggu"),
                            ("VERIFIED", "Lolos"),
                            ("REJECTED", "Ditolak"),
                            ("BLACKLISTED", "Blacklist"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "rating_avg",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mitra_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "1. Data Mitra (Driver)",
            },
        ),
        migrations.CreateModel(
            name="ArmadaKendaraan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nopol", models.CharField(max_length=15, unique=True)),
                ("merk_tahun", models.CharField(max_length=100)),
                ("is_available", models.BooleanField(default=True)),
                ("panjang_bak", models.DecimalField(decimal_places=1, max_digits=4)),
                ("lebar_bak", models.DecimalField(decimal_places=1, max_digits=4)),
                ("tinggi_bak", models.DecimalField(decimal_places=1, max_digits=4)),
                ("stnk_photo", models.ImageField(upload_to="dokumen/stnk/")),
                (
                    "kir_photo",
                    models.ImageField(blank=True, null=True, upload_to="dokumen/kir/"),
                ),
                ("foto_depan", models.ImageField(upload_to="armada_fisik/")),
                ("foto_samping", models.ImageField(upload_to="armada_fisik/")),
                ("foto_belakang", models.ImageField(upload_to="armada_fisik/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "jenis_armada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="logistics.fleet",
                        verbose_name="Jenis Truk",
                    ),
                ),
                (
                    "mitra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kendaraan_set",
                        to="logistics.mitraarmada",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "2. Aset Kendaraan Mitra",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("origin_city", models.CharField(max_length=100)),
                ("origin_address", models.TextField()),
                ("origin_lat", models.FloatField(blank=True, null=True)),
                ("origin_lng", models.FloatField(blank=True, null=True)),
                ("dest_city", models.CharField(max_length=100)),
                ("dest_address", models.TextField()),
                ("dest_lat", models.FloatField(blank=True, null=True)),
                ("dest_lng", models.FloatField(blank=True, null=True)),
                (
                    "total_distance_km",
                    models.FloatField(default=0, help_text="Jarak Riil Google Maps"),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[("STANDARD", "Standard"), ("EXPRESS", "Express")],
                        default="STANDARD",
                        max_length=20,
                    ),
                ),
                ("item_description", models.TextField(verbose_name="Deskripsi Muatan")),
                (
                    "is_doc_return",
                    models.BooleanField(
                        default=False, verbose_name="Butuh Surat Jalan Balik?"
                    ),
                ),
                (
                    "is_labor_needed",
                    models.BooleanField(default=False, verbose_name="Butuh TKBM?"),
                ),
                (
                    "factory_do_photo",
                    models.ImageField(blank=True, null=True, upload_to="orders/do/"),
                ),
                (
                    "pod_photo",
                    models.ImageField(blank=True, null=True, upload_to="orders/pod/"),
                ),
                (
                    "pod_signature",
                    models.ImageField(blank=True, null=True, upload_to="orders/sig/"),
                ),
                (
                    "base_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "addons_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "reimbursement_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "final_total_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Menunggu Konfirmasi"),
                            ("SEARCHING_DRIVER", "Mencari Driver"),
                            ("DRIVER_ASSIGNED", "Driver Menuju Lokasi"),
                            ("ARRIVED_PICKUP", "Sampai di Muat"),
                            ("IN_TRANSIT", "Dalam Perjalanan"),
                            ("ARRIVED_DROP", "Sampai di Tujuan"),
                            ("DELIVERED", "Selesai (POD Uploaded)"),
                            ("COMPLETED", "Order Tutup (Lunas)"),
                            ("CANCELLED", "Dibatalkan"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                ("cancellation_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("driver_assigned_at", models.DateTimeField(blank=True, null=True)),
                ("arrived_pickup_at", models.DateTimeField(blank=True, null=True)),
                ("loaded_at", models.DateTimeField(blank=True, null=True)),
                ("arrived_drop_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="logistics.mitraarmada",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="logistics.armadakendaraan",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "3. Transaksi Order (Logistik)",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("REIMBURSEMENT", "Reimbursement (Tol/Parkir)"),
                            ("ADDON", "Addon (Jasa)"),
                        ],
                        default="REIMBURSEMENT",
                        max_length=20,
                    ),
                ),
                ("charge_name", models.CharField(max_length=100)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "proof_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="orders/charges/"
                    ),
                ),
                ("is_verified", models.BooleanField(default=False)),
                ("admin_notes", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charges",
                        to="logistics.order",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "4. Biaya Tambahan (Charges)",
            },
        ),
    ]
