# Generated by Django 5.0.2 on 2025-11-30 15:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("logistics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MitraArmada",
            fields=[
                (
                    "mitra_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "mitra_phone_number",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="Nomor Telepon"
                    ),
                ),
                (
                    "mitra_type",
                    models.CharField(
                        choices=[
                            ("Individual", "Perorangan"),
                            ("Perusahaan", "Perusahaan Logistik"),
                        ],
                        max_length=50,
                        verbose_name="Tipe Mitra",
                    ),
                ),
                (
                    "armada_type",
                    models.CharField(
                        help_text="Ex: CDD, Fuso",
                        max_length=50,
                        verbose_name="Jenis Armada Utama",
                    ),
                ),
                (
                    "document_status",
                    models.CharField(
                        choices=[
                            ("Verified", "Terverifikasi"),
                            ("Pending", "Menunggu"),
                            ("Rejected", "Ditolak"),
                        ],
                        default="Pending",
                        max_length=20,
                        verbose_name="Status Dokumen",
                    ),
                ),
                (
                    "mitra_risk_score",
                    models.CharField(
                        choices=[
                            ("Low", "Rendah"),
                            ("Medium", "Sedang"),
                            ("High", "Tinggi"),
                        ],
                        default="Medium",
                        help_text="Kritis untuk ML",
                        max_length=10,
                        verbose_name="Skor Risiko",
                    ),
                ),
                (
                    "mitra_rating_avg",
                    models.DecimalField(
                        decimal_places=1,
                        default=5.0,
                        max_digits=2,
                        verbose_name="Rating Rata-rata",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mitra Armada",
                "verbose_name_plural": "Daftar Mitra Armada",
            },
        ),
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "config_name",
                    models.CharField(
                        max_length=100,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Nama Konfigurasi",
                    ),
                ),
                (
                    "config_value",
                    models.CharField(max_length=255, verbose_name="Nilai"),
                ),
                (
                    "config_unit",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Rupiah, Persen, Hari",
                        max_length=50,
                        null=True,
                        verbose_name="Satuan",
                    ),
                ),
            ],
            options={
                "verbose_name": "Konfigurasi Sistem",
                "verbose_name_plural": "Konfigurasi Sistem",
            },
        ),
        migrations.CreateModel(
            name="RFQ",
            fields=[
                ("rfq_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "cargo_weight_kg",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Wajib untuk ML Pricing",
                        max_digits=10,
                        verbose_name="Berat Kargo (Kg)",
                    ),
                ),
                (
                    "cargo_volume_m3",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Wajib untuk ML Pricing",
                        max_digits=10,
                        verbose_name="Volume Kargo (m³)",
                    ),
                ),
                (
                    "origin_city",
                    models.CharField(max_length=100, verbose_name="Kota Asal"),
                ),
                (
                    "dest_city",
                    models.CharField(max_length=100, verbose_name="Kota Tujuan"),
                ),
                (
                    "armada_needed_request",
                    models.CharField(
                        help_text="Ex: Pickup/CDD",
                        max_length=50,
                        verbose_name="Permintaan Armada",
                    ),
                ),
                (
                    "delivery_date_ideal",
                    models.DateField(verbose_name="Tanggal Pengiriman Ideal"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, verbose_name="Status Lelang Aktif"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client_id",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rfq_client",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "RFQ (Permintaan Harga)",
                "verbose_name_plural": "Daftar RFQ",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Transaksi",
            fields=[
                ("transaksi_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "harga_jual_final",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Harga Jual Final (Rp)",
                    ),
                ),
                (
                    "biaya_perolehan_mitra",
                    models.DecimalField(
                        decimal_places=2, max_digits=15, verbose_name="Biaya Mitra (Rp)"
                    ),
                ),
                (
                    "profit_margin_rp",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=15,
                        verbose_name="Margin Keuntungan (Rp)",
                    ),
                ),
                (
                    "status_pembayaran_mitra",
                    models.CharField(
                        choices=[
                            ("Pending", "Menunggu Pembayaran"),
                            ("Completed", "Selesai"),
                            ("Cancelled", "Dibatalkan"),
                        ],
                        default="Pending",
                        max_length=20,
                        verbose_name="Status Pembayaran",
                    ),
                ),
                (
                    "mitra_id_assigned",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transaksi_mitra",
                        to="logistics.mitraarmada",
                    ),
                ),
                (
                    "rfq_id",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transaksi",
                        to="logistics.rfq",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaksi",
                "verbose_name_plural": "Data Transaksi",
            },
        ),
        migrations.CreateModel(
            name="LogTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "milestone_name",
                    models.CharField(
                        help_text="Ex: Muatan Diambil, Dalam Perjalanan, Tiba di Tujuan",
                        max_length=100,
                        verbose_name="Nama Tahapan",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Waktu Log"),
                ),
                (
                    "is_on_time",
                    models.BooleanField(default=True, verbose_name="Tepat Waktu"),
                ),
                (
                    "incident_severity",
                    models.CharField(
                        choices=[
                            ("Low", "Rendah"),
                            ("Medium", "Sedang"),
                            ("High", "Tinggi"),
                        ],
                        default="Low",
                        max_length=10,
                        verbose_name="Tingkat Insiden",
                    ),
                ),
                (
                    "transaksi_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="logistics.transaksi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Log Tracking",
                "verbose_name_plural": "Log Pelacakan",
                "ordering": ["-timestamp"],
            },
        ),
    ]
