# Generated by Django 5.0.2 on 2025-12-01 16:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0002_mitraarmada_systemconfig_rfq_transaksi_logtracking"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="logtracking",
            name="transaksi_id",
        ),
        migrations.RemoveField(
            model_name="mitraarmada",
            name="mitra_id",
        ),
        migrations.RemoveField(
            model_name="transaksi",
            name="mitra_id_assigned",
        ),
        migrations.DeleteModel(
            name="SystemConfig",
        ),
        migrations.RemoveField(
            model_name="transaksi",
            name="rfq_id",
        ),
        migrations.AlterModelOptions(
            name="fleet",
            options={
                "ordering": ["order", "name"],
                "verbose_name_plural": "Data Armada",
            },
        ),
        migrations.AlterModelOptions(
            name="rfq",
            options={"verbose_name_plural": "Permintaan Harga (RFQ)"},
        ),
        migrations.RenameField(
            model_name="rfq",
            old_name="created_at",
            new_name="requested_at",
        ),
        migrations.RemoveField(
            model_name="fleet",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="rfq",
            name="client_id",
        ),
        migrations.RemoveField(
            model_name="rfq",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="rfq",
            name="rfq_id",
        ),
        migrations.AddField(
            model_name="rfq",
            name="client",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="rfq",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="fleet",
            name="capacity",
            field=models.CharField(
                choices=[
                    ("ECO_MPV", "Ekonomi MPV (1.7m x 1m x 0.8m) - Max 350 Kg"),
                    (
                        "BLIND_VAN",
                        "Blind Van (GranMax) (2.1m x 1.5m x 1.2m) - Max 0.7 Ton / 4 m³",
                    ),
                    (
                        "PICKUP_BAK",
                        "Pickup Bak (2.4m x 1.6m x 1.2m) - Max 800 Kg / 5 m³",
                    ),
                    (
                        "PICKUP_BOX",
                        "Pickup Box (2.4m x 1.6m x 1.2m) - Max 1 Ton / 5 m³",
                    ),
                    (
                        "L300_BAK",
                        "Pickup L300 Bak (2.4m x 1.6m x 1.2m) - Max 1 Ton / 6 m³",
                    ),
                    (
                        "CDE_BAK",
                        "Engkel (CDE) Bak (3.1m x 1.6m x 1.6m) - Max 2.5 Ton / 9 m³",
                    ),
                    (
                        "CDE_BOX",
                        "Engkel (CDE) Box (3.1m x 1.7m x 1.7m) - Max 2.2 Ton / 9 m³",
                    ),
                    (
                        "CDD_BAK",
                        "Double (CDD) Bak (4.2m x 1.9m x 2m) - Max 5 Ton / 16 m³",
                    ),
                    (
                        "CDD_BOX",
                        "Double (CDD) Box (4.2m x 2m x 2m) - Max 5 Ton / 17 m³",
                    ),
                    (
                        "CDD_LONG",
                        "CDD Long Box (5.3m x 2m x 2.2m) - Max 5.5 Ton / 24 m³",
                    ),
                    (
                        "FUSO_BAK",
                        "Fuso Ringan Bak (5.7m x 2.3m x 2.3m) - Max 8 Ton / 30 m³",
                    ),
                    (
                        "FUSO_BOX",
                        "Fuso Ringan Box (5.7m x 2.3m x 2.3m) - Max 8 Ton / 30 m³",
                    ),
                    (
                        "FUSO_BERAT",
                        "Fuso Berat (Hino Ranger) (7m x 2.4m x 2.3m) - Max 15 Ton / 40 m³",
                    ),
                    (
                        "TRONTON_BAK",
                        "Tronton Bak (9.5m x 2.4m x 2.3m) - Max 18 Ton / 50 m³",
                    ),
                    (
                        "WINGBOX",
                        "Tronton Wingbox (9.4m x 2.4m x 2.4m) - Max 18 Ton / 55 m³",
                    ),
                    (
                        "TRAILER_20",
                        "Trailer 20 Feet (6m x 2.4m x 2.4m) - Max 20 Ton / 33 m³",
                    ),
                    (
                        "TRAILER_40",
                        "Trailer 40 Feet (12m x 2.4m x 2.4m) - Max 28 Ton / 67 m³",
                    ),
                ],
                default="CDE_BAK",
                max_length=50,
                verbose_name="Tipe & Kapasitas (Deliveree Spec)",
            ),
        ),
        migrations.AlterField(
            model_name="fleet",
            name="description",
            field=models.TextField(blank=True, verbose_name="Deskripsi / Kelebihan"),
        ),
        migrations.AlterField(
            model_name="fleet",
            name="dimension",
            field=models.CharField(
                blank=True,
                help_text="Isi manual jika beda dari standar. Format: P x L x T (Meter)",
                max_length=100,
                null=True,
                verbose_name="Dimensi Custom",
            ),
        ),
        migrations.AlterField(
            model_name="fleet",
            name="fleet_type",
            field=models.CharField(
                choices=[
                    ("ECONOMY", "Ekonomi (MPV / Blind Van)"),
                    ("PICKUP", "Pickup (Bak / Box)"),
                    ("ENGKEL", "Engkel CDE (4 Roda)"),
                    ("DOUBLE", "Double CDD (6 Roda)"),
                    ("FUSO", "Fuso / Truk Besar"),
                    ("TRONTON", "Tronton / Wingbox"),
                    ("TRAILER", "Trailer / Kontainer"),
                ],
                default="PICKUP",
                max_length=20,
                verbose_name="Kategori Utama",
            ),
        ),
        migrations.AlterField(
            model_name="fleet",
            name="name",
            field=models.CharField(
                max_length=100, unique=True, verbose_name="Nama Armada"
            ),
        ),
        migrations.AlterField(
            model_name="fleet",
            name="order",
            field=models.IntegerField(
                default=0, help_text="Urutan tampilan (1 paling atas)"
            ),
        ),
        migrations.AlterField(
            model_name="fleet",
            name="volume",
            field=models.CharField(
                blank=True,
                help_text="Isi manual jika beda dari standar (Contoh: 24 CBM)",
                max_length=50,
                null=True,
                verbose_name="Volume Custom",
            ),
        ),
        migrations.AlterField(
            model_name="rfq",
            name="armada_needed_request",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="rfq",
            name="cargo_volume_m3",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="rfq",
            name="cargo_weight_kg",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="rfq",
            name="delivery_date_ideal",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="rfq",
            name="dest_city",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="rfq",
            name="origin_city",
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name="LogTracking",
        ),
        migrations.DeleteModel(
            name="MitraArmada",
        ),
        migrations.DeleteModel(
            name="Transaksi",
        ),
    ]
