# Generated by Django 5.0.2 on 2025-12-01 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0003_remove_logtracking_transaksi_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fleet",
            options={
                "ordering": ["order", "name"],
                "verbose_name_plural": "0. Master Data Jenis Armada",
            },
        ),
        migrations.AlterModelOptions(
            name="rfq",
            options={"verbose_name_plural": "9. Permintaan Harga (RFQ)"},
        ),
        migrations.AlterField(
            model_name="fleet",
            name="capacity",
            field=models.CharField(
                choices=[
                    ("ECO_MPV", "Ekonomi MPV (1.7m x 1m x 0.8m) - Max 350 Kg"),
                    (
                        "BLIND_VAN",
                        "Blind Van (GranMax) (2.1m x 1.5m x 1.2m) - Max 0.7 Ton / 4 m³",
                    ),
                    (
                        "PICKUP_BAK",
                        "Pickup Bak (2.4m x 1.6m x 1.2m) - Max 800 Kg / 5 m³",
                    ),
                    (
                        "PICKUP_BOX",
                        "Pickup Box (2.4m x 1.6m x 1.2m) - Max 1 Ton / 5 m³",
                    ),
                    (
                        "L300_BAK",
                        "Pickup L300 Bak (2.4m x 1.6m x 1.2m) - Max 1 Ton / 6 m³",
                    ),
                    (
                        "CDE_BAK",
                        "Engkel (CDE) Bak (3.1m x 1.6m x 1.6m) - Max 2.5 Ton / 9 m³",
                    ),
                    (
                        "CDE_BOX",
                        "Engkel (CDE) Box (3.1m x 1.7m x 1.7m) - Max 2.2 Ton / 9 m³",
                    ),
                    (
                        "CDD_BAK",
                        "Double (CDD) Bak (4.2m x 1.9m x 2m) - Max 5 Ton / 16 m³",
                    ),
                    (
                        "CDD_BOX",
                        "Double (CDD) Box (4.2m x 2m x 2m) - Max 5 Ton / 17 m³",
                    ),
                    (
                        "CDD_LONG",
                        "CDD Long Box (5.3m x 2m x 2.2m) - Max 5.5 Ton / 24 m³",
                    ),
                    (
                        "FUSO_BAK",
                        "Fuso Ringan Bak (5.7m x 2.3m x 2.3m) - Max 8 Ton / 30 m³",
                    ),
                    (
                        "FUSO_BOX",
                        "Fuso Ringan Box (5.7m x 2.3m x 2.3m) - Max 8 Ton / 30 m³",
                    ),
                    (
                        "FUSO_BERAT",
                        "Fuso Berat (Hino Ranger) (7m x 2.4m x 2.3m) - Max 15 Ton / 40 m³",
                    ),
                    (
                        "TRONTON_BAK",
                        "Tronton Bak (9.5m x 2.4m x 2.3m) - Max 18 Ton / 50 m³",
                    ),
                    (
                        "WINGBOX",
                        "Tronton Wingbox (9.4m x 2.4m x 2.4m) - Max 18 Ton / 55 m³",
                    ),
                    (
                        "TRAILER_20",
                        "Trailer 20 Feet (6m x 2.4m x 2.4m) - Max 20 Ton / 33 m³",
                    ),
                    (
                        "TRAILER_40",
                        "Trailer 40 Feet (12m x 2.4m x 2.4m) - Max 28 Ton / 67 m³",
                    ),
                ],
                default="CDE_BAK",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="fleet",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="fleet",
            name="dimension",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Dimensi Custom"
            ),
        ),
        migrations.AlterField(
            model_name="fleet",
            name="fleet_type",
            field=models.CharField(
                choices=[
                    ("ECONOMY", "Ekonomi (MPV / Blind Van)"),
                    ("PICKUP", "Pickup (Bak / Box)"),
                    ("ENGKEL", "Engkel CDE (4 Roda)"),
                    ("DOUBLE", "Double CDD (6 Roda)"),
                    ("FUSO", "Fuso / Truk Besar"),
                    ("TRONTON", "Tronton / Wingbox"),
                    ("TRAILER", "Trailer / Container"),
                ],
                default="PICKUP",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="fleet",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="fleets/"),
        ),
        migrations.AlterField(
            model_name="fleet",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="fleet",
            name="volume",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Volume Custom"
            ),
        ),
        migrations.CreateModel(
            name="MitraArmada",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name_ktp",
                    models.CharField(
                        max_length=150, verbose_name="Nama Lengkap Sesuai KTP"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="No WhatsApp Aktif"
                    ),
                ),
                (
                    "emergency_name",
                    models.CharField(
                        max_length=100, verbose_name="Nama Kontak Darurat"
                    ),
                ),
                (
                    "emergency_phone",
                    models.CharField(max_length=15, verbose_name="No Telp Darurat"),
                ),
                (
                    "emergency_relation",
                    models.CharField(max_length=50, verbose_name="Hubungan"),
                ),
                (
                    "domicile_city",
                    models.CharField(
                        default="Jakarta",
                        max_length=100,
                        verbose_name="Kota Domisili (Basecamp)",
                    ),
                ),
                ("domicile_address", models.TextField(verbose_name="Alamat Lengkap")),
                (
                    "mitra_type",
                    models.CharField(
                        choices=[
                            ("OWNER_OPERATOR", "Pemilik Unit & Supir"),
                            ("DRIVER", "Supir (Bawa Unit Orang Lain)"),
                        ],
                        default="OWNER_OPERATOR",
                        max_length=20,
                    ),
                ),
                (
                    "ktp_photo",
                    models.ImageField(
                        upload_to="dokumen/ktp/", verbose_name="Foto KTP"
                    ),
                ),
                (
                    "sim_photo",
                    models.ImageField(
                        upload_to="dokumen/sim/", verbose_name="Foto SIM"
                    ),
                ),
                (
                    "selfie_photo",
                    models.ImageField(
                        upload_to="dokumen/selfie/",
                        verbose_name="Foto Selfie Pegang KTP",
                    ),
                ),
                (
                    "skck_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="dokumen/skck/",
                        verbose_name="Foto SKCK",
                    ),
                ),
                (
                    "bank_name",
                    models.CharField(
                        choices=[
                            ("BCA", "Bank Central Asia (BCA)"),
                            ("BRI", "Bank Rakyat Indonesia (BRI)"),
                            ("MANDIRI", "Bank Mandiri"),
                            ("BNI", "Bank Negara Indonesia (BNI)"),
                            ("LAINNYA", "Bank Lainnya"),
                        ],
                        default="BCA",
                        max_length=20,
                    ),
                ),
                (
                    "bank_account_number",
                    models.CharField(max_length=50, verbose_name="Nomor Rekening"),
                ),
                (
                    "bank_account_holder",
                    models.CharField(
                        max_length=150, verbose_name="Nama Pemilik Rekening"
                    ),
                ),
                (
                    "document_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Menunggu Verifikasi"),
                            ("VERIFIED", "Terverifikasi (Lolos)"),
                            ("REJECTED", "Ditolak (Data Tidak Sesuai)"),
                            ("BLACKLISTED", "Di-Blacklist (Bermasalah)"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "admin_notes",
                    models.TextField(blank=True, help_text="Catatan Admin"),
                ),
                (
                    "rating_avg",
                    models.DecimalField(decimal_places=2, default=5.0, max_digits=3),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mitra_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "1. Data Mitra (Orang)",
            },
        ),
        migrations.CreateModel(
            name="ArmadaKendaraan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nopol",
                    models.CharField(
                        max_length=15, unique=True, verbose_name="Plat Nomor"
                    ),
                ),
                (
                    "merk_tahun",
                    models.CharField(max_length=100, verbose_name="Merk & Tahun"),
                ),
                (
                    "current_location_city",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Posisi Terkini (Kota)",
                    ),
                ),
                (
                    "is_available",
                    models.BooleanField(default=True, verbose_name="Siap Muat"),
                ),
                (
                    "panjang_bak",
                    models.DecimalField(
                        decimal_places=1, max_digits=4, verbose_name="P (Meter)"
                    ),
                ),
                (
                    "lebar_bak",
                    models.DecimalField(
                        decimal_places=1, max_digits=4, verbose_name="L (Meter)"
                    ),
                ),
                (
                    "tinggi_bak",
                    models.DecimalField(
                        decimal_places=1, max_digits=4, verbose_name="T (Meter)"
                    ),
                ),
                (
                    "kapasitas_maks",
                    models.CharField(max_length=50, verbose_name="Kapasitas Maks"),
                ),
                (
                    "stnk_photo",
                    models.ImageField(
                        upload_to="dokumen/stnk/", verbose_name="Foto STNK"
                    ),
                ),
                (
                    "kir_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="dokumen/kir/",
                        verbose_name="Foto KIR",
                    ),
                ),
                (
                    "foto_depan",
                    models.ImageField(
                        upload_to="armada_fisik/", verbose_name="Foto Depan"
                    ),
                ),
                (
                    "foto_samping",
                    models.ImageField(
                        upload_to="armada_fisik/", verbose_name="Foto Samping"
                    ),
                ),
                (
                    "foto_belakang",
                    models.ImageField(
                        upload_to="armada_fisik/", verbose_name="Foto Belakang"
                    ),
                ),
                (
                    "foto_dalam",
                    models.ImageField(
                        upload_to="armada_fisik/", verbose_name="Foto Dalam"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "jenis_armada",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="logistics.fleet",
                        verbose_name="Jenis Truk",
                    ),
                ),
                (
                    "mitra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kendaraan_set",
                        to="logistics.mitraarmada",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "2. Aset Kendaraan Mitra",
            },
        ),
    ]
