# Generated by Django 5.0.2 on 2025-12-03 20:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0004_alter_fleet_options_alter_rfq_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MasterPricingRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fleet_type",
                    models.CharField(
                        choices=[
                            ("ECONOMY", "Ekonomi (MPV / Blind Van)"),
                            ("PICKUP", "Pickup (Bak / Box)"),
                            ("ENGKEL", "Engkel CDE (4 Roda)"),
                            ("DOUBLE", "Double CDD (6 Roda)"),
                            ("FUSO", "Fuso / Truk Besar"),
                            ("TRONTON", "Tronton / Wingbox"),
                            ("TRAILER", "Trailer / Container"),
                        ],
                        max_length=20,
                        unique=True,
                        verbose_name="Kategori Armada",
                    ),
                ),
                (
                    "base_rate_per_km",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Harga modal driver per KM",
                        max_digits=10,
                    ),
                ),
                (
                    "min_distance_km",
                    models.IntegerField(default=10, help_text="Jarak minimum charge"),
                ),
                (
                    "min_price_lumpsum",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Harga minimum jika jarak pendek",
                        max_digits=12,
                    ),
                ),
                (
                    "loading_unloading_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=50000,
                        help_text="Biaya TKBM standar per orang",
                        max_digits=10,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "0. Master Pricing Rules (HPP)",
            },
        ),
        migrations.AlterField(
            model_name="armadakendaraan",
            name="current_location_city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="armadakendaraan",
            name="foto_belakang",
            field=models.ImageField(upload_to="armada_fisik/"),
        ),
        migrations.AlterField(
            model_name="armadakendaraan",
            name="foto_dalam",
            field=models.ImageField(upload_to="armada_fisik/"),
        ),
        migrations.AlterField(
            model_name="armadakendaraan",
            name="foto_depan",
            field=models.ImageField(upload_to="armada_fisik/"),
        ),
        migrations.AlterField(
            model_name="armadakendaraan",
            name="foto_samping",
            field=models.ImageField(upload_to="armada_fisik/"),
        ),
        migrations.AlterField(
            model_name="armadakendaraan",
            name="is_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="armadakendaraan",
            name="kapasitas_maks",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="armadakendaraan",
            name="kir_photo",
            field=models.ImageField(blank=True, null=True, upload_to="dokumen/kir/"),
        ),
        migrations.AlterField(
            model_name="armadakendaraan",
            name="lebar_bak",
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name="armadakendaraan",
            name="merk_tahun",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="armadakendaraan",
            name="nopol",
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name="armadakendaraan",
            name="panjang_bak",
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name="armadakendaraan",
            name="stnk_photo",
            field=models.ImageField(upload_to="dokumen/stnk/"),
        ),
        migrations.AlterField(
            model_name="armadakendaraan",
            name="tinggi_bak",
            field=models.DecimalField(decimal_places=1, max_digits=4),
        ),
        migrations.AlterField(
            model_name="mitraarmada",
            name="admin_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="mitraarmada",
            name="bank_account_holder",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="mitraarmada",
            name="bank_account_number",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="mitraarmada",
            name="bank_name",
            field=models.CharField(
                choices=[
                    ("BCA", "BCA"),
                    ("BRI", "BRI"),
                    ("MANDIRI", "Mandiri"),
                    ("BNI", "BNI"),
                    ("LAINNYA", "Lainnya"),
                ],
                default="BCA",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mitraarmada",
            name="document_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Menunggu"),
                    ("VERIFIED", "Lolos"),
                    ("REJECTED", "Ditolak"),
                    ("BLACKLISTED", "Blacklist"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mitraarmada",
            name="domicile_address",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="mitraarmada",
            name="domicile_city",
            field=models.CharField(default="Jakarta", max_length=100),
        ),
        migrations.AlterField(
            model_name="mitraarmada",
            name="emergency_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="mitraarmada",
            name="emergency_phone",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="mitraarmada",
            name="emergency_relation",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="mitraarmada",
            name="full_name_ktp",
            field=models.CharField(max_length=150, verbose_name="Nama KTP"),
        ),
        migrations.AlterField(
            model_name="mitraarmada",
            name="ktp_photo",
            field=models.ImageField(upload_to="dokumen/ktp/"),
        ),
        migrations.AlterField(
            model_name="mitraarmada",
            name="mitra_type",
            field=models.CharField(
                choices=[
                    ("OWNER_OPERATOR", "Pemilik Unit & Supir"),
                    ("DRIVER", "Supir"),
                ],
                default="OWNER_OPERATOR",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="mitraarmada",
            name="phone_number",
            field=models.CharField(max_length=15, unique=True, verbose_name="WhatsApp"),
        ),
        migrations.AlterField(
            model_name="mitraarmada",
            name="selfie_photo",
            field=models.ImageField(upload_to="dokumen/selfie/"),
        ),
        migrations.AlterField(
            model_name="mitraarmada",
            name="sim_photo",
            field=models.ImageField(upload_to="dokumen/sim/"),
        ),
        migrations.AlterField(
            model_name="mitraarmada",
            name="skck_photo",
            field=models.ImageField(blank=True, null=True, upload_to="dokumen/skck/"),
        ),
        migrations.CreateModel(
            name="RFQRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("origin_city", models.CharField(max_length=100)),
                ("dest_city", models.CharField(max_length=100)),
                (
                    "distance_km",
                    models.FloatField(default=0, help_text="Estimasi Jarak via Maps"),
                ),
                ("item_name", models.CharField(default="-", max_length=200)),
                (
                    "cargo_weight_kg",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "cargo_volume_m3",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "armada_needed_request",
                    models.CharField(
                        choices=[
                            ("ECONOMY", "Ekonomi (MPV / Blind Van)"),
                            ("PICKUP", "Pickup (Bak / Box)"),
                            ("ENGKEL", "Engkel CDE (4 Roda)"),
                            ("DOUBLE", "Double CDD (6 Roda)"),
                            ("FUSO", "Fuso / Truk Besar"),
                            ("TRONTON", "Tronton / Wingbox"),
                            ("TRAILER", "Trailer / Container"),
                        ],
                        max_length=20,
                    ),
                ),
                ("delivery_date_ideal", models.DateField(blank=True, null=True)),
                (
                    "req_tkbm",
                    models.BooleanField(
                        default=False, verbose_name="Butuh Kuli Angkut?"
                    ),
                ),
                (
                    "user_budget_offer",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Budget ajuan user",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "is_corporate_order",
                    models.BooleanField(
                        default=False, help_text="Order Perusahaan (Kena Pajak)"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Mencari Driver"),
                            ("NEGOTIATION", "Nego Budget"),
                            ("MATCHED", "Dapat Driver"),
                            ("COMPLETED", "Selesai"),
                            ("CANCELLED", "Batal"),
                        ],
                        default="OPEN",
                        max_length=20,
                    ),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rfqs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "3. Permintaan Harga (RFQ)",
            },
        ),
        migrations.CreateModel(
            name="Quotation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system_base_price",
                    models.DecimalField(
                        decimal_places=2, help_text="Harga Normal Sistem", max_digits=12
                    ),
                ),
                (
                    "final_offered_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Harga Final (Setelah Nego)",
                        max_digits=12,
                    ),
                ),
                ("is_budget_accepted", models.BooleanField(default=False)),
                (
                    "admin_notes",
                    models.TextField(
                        blank=True,
                        help_text="Pesan untuk User (misal: Disetujui tapi LTL)",
                        null=True,
                    ),
                ),
                ("valid_until", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "rfq",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotation",
                        to="logistics.rfqrequest",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "4. Quotations (Penawaran)",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "selling_price_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Total Tagihan Customer",
                    ),
                ),
                (
                    "mitra_net_income",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Pendapatan Bersih Driver",
                    ),
                ),
                (
                    "tkbm_cost",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Biaya Kuli Bongkar Muat",
                        max_digits=10,
                    ),
                ),
                (
                    "toll_parking_reimburse",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Biaya Tol/Parkir (Jika ada)",
                        max_digits=10,
                    ),
                ),
                (
                    "gross_profit",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        verbose_name="Gross Profit Kantor",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_PAYMENT", "Menunggu Pembayaran"),
                            ("PAID", "Lunas (Siap Jalan)"),
                            ("PICKUP_PROCESS", "Proses Muat"),
                            ("ON_DELIVERY", "Dalam Perjalanan"),
                            ("DELIVERED", "Barang Sampai"),
                            ("DONE", "Selesai (Dana Cair)"),
                            ("COMPLAINT", "Ada Komplain"),
                        ],
                        default="PENDING_PAYMENT",
                        max_length=20,
                    ),
                ),
                (
                    "payment_proof",
                    models.ImageField(blank=True, null=True, upload_to="payments/"),
                ),
                (
                    "weather_condition",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_asset",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="logistics.armadakendaraan",
                    ),
                ),
                (
                    "assigned_driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "quotation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="logistics.quotation",
                    ),
                ),
                (
                    "rfq",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="logistics.rfqrequest",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "5. Transaksi (Financial)",
            },
        ),
        migrations.DeleteModel(
            name="RFQ",
        ),
    ]
