# Generated by Django 5.0.2 on 2025-12-10 10:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("logistics", "0005_masterpricingrule_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Promo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Judul Promo")),
                ("description", models.TextField(verbose_name="Deskripsi Singkat")),
                (
                    "promo_code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Kode Voucher"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="promos/", verbose_name="Gambar Banner"
                    ),
                ),
                ("valid_until", models.DateField(verbose_name="Berlaku Sampai")),
                ("is_active", models.BooleanField(default=True, verbose_name="Aktif?")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "5. Promo & Voucher",
            },
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="quotation",
        ),
        migrations.RemoveField(
            model_name="rfqrequest",
            name="client",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="rfq",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="assigned_asset",
        ),
        migrations.RemoveField(
            model_name="transaction",
            name="assigned_driver",
        ),
        migrations.AlterModelOptions(
            name="mitraarmada",
            options={"verbose_name_plural": "1. Data Mitra (Driver)"},
        ),
        migrations.RemoveField(
            model_name="armadakendaraan",
            name="current_location_city",
        ),
        migrations.RemoveField(
            model_name="armadakendaraan",
            name="foto_dalam",
        ),
        migrations.RemoveField(
            model_name="armadakendaraan",
            name="kapasitas_maks",
        ),
        migrations.RemoveField(
            model_name="mitraarmada",
            name="admin_notes",
        ),
        migrations.RemoveField(
            model_name="mitraarmada",
            name="emergency_relation",
        ),
        migrations.AddField(
            model_name="masterpricingrule",
            name="base_fare",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Harga Buka Pintu (Flagfall)",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="masterpricingrule",
            name="doc_return_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=25000,
                help_text="Biaya Jasa Dokumen Balik",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="masterpricingrule",
            name="sla_express_multiplier",
            field=models.DecimalField(
                decimal_places=2,
                default=1.5,
                help_text="Pengali Express (Default: 1.5x)",
                max_digits=3,
            ),
        ),
        migrations.AddField(
            model_name="mitraarmada",
            name="admin_risk_notes",
            field=models.TextField(
                blank=True, help_text="Catatan internal pelanggaran mitra"
            ),
        ),
        migrations.AddField(
            model_name="mitraarmada",
            name="risk_status",
            field=models.CharField(
                choices=[
                    ("SAFE", "🟢 Aman / Verified"),
                    ("CAUTION", "🟡 Waspada (Perlu Review)"),
                    ("BLACKLIST", "🔴 Blacklist (Dilarang)"),
                ],
                default="SAFE",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="CachedDistance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("origin_lat", models.DecimalField(decimal_places=8, max_digits=10)),
                ("origin_lng", models.DecimalField(decimal_places=8, max_digits=10)),
                ("dest_lat", models.DecimalField(decimal_places=8, max_digits=10)),
                ("dest_lng", models.DecimalField(decimal_places=8, max_digits=10)),
                (
                    "distance_km",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Jarak tempuh riil (km)",
                        max_digits=10,
                    ),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(help_text="Durasi tempuh (menit)"),
                ),
                (
                    "toll_fee_idr",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Estimasi biaya tol (IDR)",
                        max_digits=12,
                    ),
                ),
                ("cached_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Cached Distance",
                "unique_together": {
                    ("origin_lat", "origin_lng", "dest_lat", "dest_lng")
                },
            },
        ),
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=15, unique=True)),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nama PT/CV (Jika Corporate)",
                    ),
                ),
                (
                    "risk_status",
                    models.CharField(
                        choices=[
                            ("SAFE", "🟢 Aman / Verified"),
                            ("CAUTION", "🟡 Waspada (Perlu Review)"),
                            ("BLACKLIST", "🔴 Blacklist (Dilarang)"),
                        ],
                        default="SAFE",
                        max_length=20,
                    ),
                ),
                (
                    "admin_risk_notes",
                    models.TextField(
                        blank=True,
                        help_text="Catatan internal dosa/pelanggaran customer",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "1. Data Customer (Shipper)",
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("origin_city", models.CharField(max_length=100)),
                ("origin_address", models.TextField()),
                ("origin_lat", models.FloatField(blank=True, null=True)),
                ("origin_lng", models.FloatField(blank=True, null=True)),
                ("dest_city", models.CharField(max_length=100)),
                ("dest_address", models.TextField()),
                ("dest_lat", models.FloatField(blank=True, null=True)),
                ("dest_lng", models.FloatField(blank=True, null=True)),
                (
                    "total_distance_km",
                    models.FloatField(default=0, help_text="Jarak Riil Google Maps"),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[("STANDARD", "Standard"), ("EXPRESS", "Express")],
                        default="STANDARD",
                        max_length=20,
                    ),
                ),
                ("item_description", models.TextField(verbose_name="Deskripsi Muatan")),
                (
                    "is_doc_return",
                    models.BooleanField(
                        default=False, verbose_name="Butuh Surat Jalan Balik?"
                    ),
                ),
                (
                    "is_labor_needed",
                    models.BooleanField(default=False, verbose_name="Butuh TKBM?"),
                ),
                (
                    "factory_do_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="orders/do/",
                        verbose_name="Foto Surat Jalan Pabrik",
                    ),
                ),
                (
                    "pod_photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="orders/pod/",
                        verbose_name="Foto Barang Sampai (POD)",
                    ),
                ),
                (
                    "pod_signature",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="orders/sig/",
                        verbose_name="Tanda Tangan Penerima",
                    ),
                ),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Harga Jarak",
                        max_digits=12,
                    ),
                ),
                (
                    "addons_price",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Harga Tambahan (TKBM/Doc)",
                        max_digits=12,
                    ),
                ),
                (
                    "reimbursement_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Total Tol/Parkir yang disetujui",
                        max_digits=12,
                    ),
                ),
                (
                    "final_total_price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Menunggu Konfirmasi"),
                            ("SEARCHING_DRIVER", "Mencari Driver"),
                            ("DRIVER_ASSIGNED", "Driver Menuju Lokasi"),
                            ("ARRIVED_PICKUP", "Sampai di Muat"),
                            ("IN_TRANSIT", "Dalam Perjalanan"),
                            ("ARRIVED_DROP", "Sampai di Tujuan"),
                            ("DELIVERED", "Selesai (POD Uploaded)"),
                            ("COMPLETED", "Order Tutup (Lunas)"),
                            ("CANCELLED", "Dibatalkan"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                ("cancellation_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("driver_assigned_at", models.DateTimeField(blank=True, null=True)),
                ("arrived_pickup_at", models.DateTimeField(blank=True, null=True)),
                ("loaded_at", models.DateTimeField(blank=True, null=True)),
                ("arrived_drop_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="logistics.mitraarmada",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="logistics.armadakendaraan",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "3. Transaksi Order (Logistik)",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderCharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("REIMBURSEMENT", "Reimbursement (Tol/Parkir)"),
                            ("ADDON", "Addon (Jasa)"),
                        ],
                        default="REIMBURSEMENT",
                        max_length=20,
                    ),
                ),
                (
                    "charge_name",
                    models.CharField(
                        help_text="Contoh: Tol Cipali, Parkir Gudang", max_length=100
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "proof_image",
                    models.ImageField(
                        blank=True,
                        help_text="Foto Struk/Karcis",
                        null=True,
                        upload_to="orders/charges/",
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="Disetujui Admin?"),
                ),
                (
                    "admin_notes",
                    models.CharField(
                        blank=True, help_text="Alasan tolak jika ada", max_length=200
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="charges",
                        to="logistics.order",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "4. Biaya Tambahan (Charges)",
            },
        ),
        migrations.DeleteModel(
            name="Quotation",
        ),
        migrations.DeleteModel(
            name="RFQRequest",
        ),
        migrations.DeleteModel(
            name="Transaction",
        ),
    ]
